sudo: false
language: ruby
cache: bundler
before_install: gem update bundler
matrix:
  include:
    - rvm: 2.1.0
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3.3
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: rbx-3
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: rbx-3
  fast_finish: true
script: bundle exec rake
