os: linux
language: ruby
cache:
  bundler: true
before_install:
  - gem update --system
  - gem install bundler
before_script: ./travis_scripts/before_script.sh
jobs:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 3.0
    - rvm: ruby-head
    - rvm: jruby-9.1.17.0
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: rbx-3
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.17.0
    - rvm: rbx-3
  fast_finish: true

script:
  - ./travis_scripts/script.sh
  - bundle exec cucumber features --format progress --color
  - bundle exec rake reek
  - bundle exec mdl .
  - bundle exec rubocop
